/* Generated by opensource COBOL 4J 2.0.0 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import jp.osscons.opensourcecobol.libcobj.sql.*;
import java.util.Optional;

public class SALESPROG implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return SALESPROG_(0, argStorages);
  }

  @Override
  public void cancel() {
    SALESPROG_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int SALESPROG_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	h_SLS_FILE.close (0, null);
    	h_RPT_FILE.close (0, null);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("SALESPROG");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("SALESPROG");

      b_RETURN_CODE.set((int)0);
      b_WS_EOF.setByte(0, 'N');      b_WS_COUNT.fillBytes (48, 5);
      b_WS_QTY__WS_CALC_AREA.fillBytes('0', 28);
      b_WS_TIER__WS_CALC_AREA.fillBytes(' ', 10);

      h_SLS_FILE = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "SLS-FILE",
      /* file_status = */ h_SLS_FILE_status,
      /* assign = */ c_1_data,
      /* record = */ f_SLS_FILE_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 39,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );
      h_RPT_FILE = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "RPT-FILE",
      /* file_status = */ h_RPT_FILE_status,
      /* assign = */ c_2_data,
      /* record = */ f_RPT_FILE_record,
      /* record_size = */ null,
      /* record_min = */ 0,
      /* record_max = */ 41,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)1,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)0,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );

      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_SALESPROG);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_SALESPROG]);
      }
    },
    /* Entry SALESPROG */
    new CobolControl(l_SALESPROG, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__MAIN_SECTION]);
      }
    },
    /* MAIN-SECTION */
    new CobolControl(l_MAIN_SECTION__MAIN_SECTION, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/SALESPROG.cob:31: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_SLS_FILE.open (1, 0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/SALESPROG.cob:32: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_RPT_FILE.open (2, 1, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/SALESPROG.cob:33: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_3_SALES);
        }
        /* src/SALESPROG.cob:34: PERFORM */
        for (;;)
        {
          if (((long)(Byte.toUnsignedInt(b_WS_EOF.getByte(0)) - (int)89) == 0L))
            break;
          {
            /* src/SALESPROG.cob:35: READ */
            CobolRuntimeException.code = 0;
            {
              h_SLS_FILE.read (0, null, 1);
            }
            if (CobolRuntimeException.code != 0)
            {
              if (CobolRuntimeException.code == 0x0501)
              {
                {
                  /* src/SALESPROG.cob:37: MOVE */
                  {
                    b_WS_EOF.setByte(89);
                  }
                }
              }
              else
              {
                /* PERFORM Default Error Handler */
                CobolControl.perform(contList, l_Default_Error_Handler).run();
              }
            }
            else
            {
              {
                /* src/SALESPROG.cob:39: DISPLAY */
                {
                  CobolTerminal.display (0, 1, 2, c_4_RAW, f_SALES_RECORD);
                }
                /* src/SALESPROG.cob:40: PERFORM */
                /* PERFORM PROCESS-SALE */
                CobolControl.perform(contList, l_MAIN_SECTION__PROCESS_SALE).run();
              }
            }
          }
        }
        /* src/SALESPROG.cob:43: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_SLS_FILE.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/SALESPROG.cob:44: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_RPT_FILE.close (0, null);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* src/SALESPROG.cob:45: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_5_SALES, f_WS_COUNT);
        }
        /* src/SALESPROG.cob:46: DISPLAY */
        {
          CobolTerminal.display (0, 1, 1, c_6_SALES);
        }
        /* src/SALESPROG.cob:47: GOBACK */
        {
          if(true) return Optional.of(contList[contList.length - 1]);
        }

        return Optional.of(contList[l_MAIN_SECTION__PROCESS_SALE]);
      }
    },
    /* PROCESS-SALE */
    new CobolControl(l_MAIN_SECTION__PROCESS_SALE, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/SALESPROG.cob:49: ADD */
        {
          f_WS_COUNT.add (c_7_1, 4);
        }
        /* src/SALESPROG.cob:50: MOVE */
        {
          b_WS_QTY__WS_CALC_AREA.setBytes (b_SLS_QTY__SALES_RECORD, 5);
        }
        /* src/SALESPROG.cob:51: MOVE */
        {
          b_WS_UNIT_PRICE__WS_CALC_AREA.setBytes (b_SLS_UNIT_PRICE__SALES_RECORD, 9);
        }
        /* src/SALESPROG.cob:52: MOVE */
        {
          b_WS_DISCOUNT__WS_CALC_AREA.fillBytes (48, 3);
        }
        /* src/SALESPROG.cob:53: CALL */
        {
          CobolModule.getCurrentModule ().setParameters (f_WS_CALC_AREA);
          CobolCallParams.callParams = 1;
          call_SALESCALC = CobolResolve.resolve(null, "SALESCALC", call_SALESCALC);
          b_RETURN_CODE.set (call_SALESCALC.run (b_WS_CALC_AREA));
        }
        /* src/SALESPROG.cob:54: MOVE */
        {
          b_RPT_REP_ID__RPT_REC.setBytes (b_SLS_REP_ID__SALES_RECORD, 8);
        }
        /* src/SALESPROG.cob:55: MOVE */
        {
          b_RPT_PRODUCT__RPT_REC.setBytes (b_SLS_PRODUCT__SALES_RECORD, 12);
        }
        /* src/SALESPROG.cob:56: MOVE */
        {
          b_RPT_TOTAL__RPT_REC.setBytes (b_WS_TOTAL__WS_CALC_AREA, 11);
        }
        /* src/SALESPROG.cob:57: MOVE */
        {
          b_RPT_TIER__RPT_REC.setBytes (b_WS_TIER__WS_CALC_AREA, 10);
        }
        /* src/SALESPROG.cob:58: WRITE */
        CobolRuntimeException.code = 0;
        {
          h_RPT_FILE.write (f_RPT_REC, 2162689, null);
        }
        if (CobolRuntimeException.code != 0)
        {
          /* PERFORM Default Error Handler */
          CobolControl.perform(contList, l_Default_Error_Handler).run();
        }


        return Optional.of(CobolControl.pure());
      }
    },
    /* Default Error Handler */
    new CobolControl(l_Default_Error_Handler, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        if ((CobolFile.errorFile.flag_select_features & CobolFile.COB_SELECT_FILE_STATUS) == 0) {
        	CobolFile.defaultErrorHandle ();
        	CobolStopRunException.stopRunAndThrow (1);
        }

        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new SALESPROG().SALESPROG_(0);
    CobolStopRunException.stopRun();
  }

  public SALESPROG()
  {
    init();
  }

  public void init() 
  {
    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : SALESPROG */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
    b_SLS_FILE_record = new CobolDataStorage(39);	/* SLS-FILE_record */
    b_RPT_FILE_record = new CobolDataStorage(41);	/* RPT-FILE_record */
    b_WS_EOF = new CobolDataStorage(1);	/* WS-EOF */
    b_WS_COUNT = new CobolDataStorage(5);	/* WS-COUNT */
    b_WS_CALC_AREA = new CobolDataStorage(38);	/* WS-CALC-AREA */
    b_RPT_PRODUCT__RPT_REC = b_RPT_FILE_record.getSubDataStorage(8);
    b_RPT_REC = b_RPT_FILE_record;
    b_RPT_REP_ID__RPT_REC = b_RPT_FILE_record;
    b_RPT_TIER__RPT_REC = b_RPT_FILE_record.getSubDataStorage(31);
    b_RPT_TOTAL__RPT_REC = b_RPT_FILE_record.getSubDataStorage(20);
    b_SALES_RECORD = b_SLS_FILE_record;
    b_SLS_PRODUCT__SALES_RECORD = b_SLS_FILE_record.getSubDataStorage(13);
    b_SLS_QTY__SALES_RECORD = b_SLS_FILE_record.getSubDataStorage(25);
    b_SLS_REP_ID__SALES_RECORD = b_SLS_FILE_record;
    b_SLS_UNIT_PRICE__SALES_RECORD = b_SLS_FILE_record.getSubDataStorage(30);
    b_WS_DISCOUNT__WS_CALC_AREA = b_WS_CALC_AREA.getSubDataStorage(14);
    b_WS_QTY__WS_CALC_AREA = b_WS_CALC_AREA;
    b_WS_TIER__WS_CALC_AREA = b_WS_CALC_AREA.getSubDataStorage(28);
    b_WS_TOTAL__WS_CALC_AREA = b_WS_CALC_AREA.getSubDataStorage(17);
    b_WS_UNIT_PRICE__WS_CALC_AREA = b_WS_CALC_AREA.getSubDataStorage(5);

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : SALESPROG */
    f_SALES_RECORD	= CobolFieldFactory.makeCobolField(39, b_SALES_RECORD, a_2_Group);	/* SALES-RECORD */
    f_SLS_FILE_record	= CobolFieldFactory.makeCobolField(39, b_SLS_FILE_record, a_1_Alphanumeric);	/* SLS-FILE_record */
    f_RPT_REC	= CobolFieldFactory.makeCobolField(41, b_RPT_REC, a_2_Group);	/* RPT-REC */
    f_RPT_FILE_record	= CobolFieldFactory.makeCobolField(41, b_RPT_FILE_record, a_1_Alphanumeric);	/* RPT-FILE_record */
    f_WS_COUNT	= CobolFieldFactory.makeCobolField(5, b_WS_COUNT, a_3_NumericDisplay_Digits5_Scale0);	/* WS-COUNT */
    f_WS_CALC_AREA	= CobolFieldFactory.makeCobolField(38, b_WS_CALC_AREA, a_2_Group);	/* WS-CALC-AREA */

    /* End of fields */


    /* Constants */

    c_1_data	= CobolFieldFactory.makeCobolField(str_0_data, a_1_Alphanumeric);
    c_2_data	= CobolFieldFactory.makeCobolField(str_1_data, a_1_Alphanumeric);
    c_3_SALES	= CobolFieldFactory.makeCobolField(str_2_SALES, a_1_Alphanumeric);
    c_4_RAW	= CobolFieldFactory.makeCobolField(str_3_RAW, a_1_Alphanumeric);
    c_5_SALES	= CobolFieldFactory.makeCobolField(str_4_SALES, a_1_Alphanumeric);
    c_6_SALES	= CobolFieldFactory.makeCobolField(str_5_SALES, a_1_Alphanumeric);
    c_7_1	= CobolFieldFactory.makeCobolField(1, "1", a_4_NumericDisplay_Digits1_Scale0);

  }

  private void initAttr() {
    /* Attributes */

    a_1_Alphanumeric = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_ALPHANUMERIC,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_Group = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_GROUP,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits5_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 5,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_NumericDisplay_Digits1_Scale0 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 1,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Data storage */

  /* PROGRAM-ID : SALESPROG */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_SLS_FILE_record;	/* SLS-FILE_record */
  private CobolDataStorage b_RPT_FILE_record;	/* RPT-FILE_record */
  private CobolDataStorage b_WS_EOF;	/* WS-EOF */
  private CobolDataStorage b_WS_COUNT;	/* WS-COUNT */
  private CobolDataStorage b_WS_CALC_AREA;	/* WS-CALC-AREA */
  private CobolDataStorage b_RPT_PRODUCT__RPT_REC;
  private CobolDataStorage b_RPT_REC;
  private CobolDataStorage b_RPT_REP_ID__RPT_REC;
  private CobolDataStorage b_RPT_TIER__RPT_REC;
  private CobolDataStorage b_RPT_TOTAL__RPT_REC;
  private CobolDataStorage b_SALES_RECORD;
  private CobolDataStorage b_SLS_PRODUCT__SALES_RECORD;
  private CobolDataStorage b_SLS_QTY__SALES_RECORD;
  private CobolDataStorage b_SLS_REP_ID__SALES_RECORD;
  private CobolDataStorage b_SLS_UNIT_PRICE__SALES_RECORD;
  private CobolDataStorage b_WS_DISCOUNT__WS_CALC_AREA;
  private CobolDataStorage b_WS_QTY__WS_CALC_AREA;
  private CobolDataStorage b_WS_TIER__WS_CALC_AREA;
  private CobolDataStorage b_WS_TOTAL__WS_CALC_AREA;
  private CobolDataStorage b_WS_UNIT_PRICE__WS_CALC_AREA;

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : SALESPROG */
  private AbstractCobolField f_SALES_RECORD;	/* SALES-RECORD */
  private AbstractCobolField f_SLS_FILE_record;	/* SLS-FILE_record */
  private AbstractCobolField f_RPT_REC;	/* RPT-REC */
  private AbstractCobolField f_RPT_FILE_record;	/* RPT-FILE_record */
  private AbstractCobolField f_WS_COUNT;	/* WS-COUNT */
  private AbstractCobolField f_WS_CALC_AREA;	/* WS-CALC-AREA */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_7_1;
  private AbstractCobolField c_6_SALES;
  private AbstractCobolField c_5_SALES;
  private AbstractCobolField c_4_RAW;
  private AbstractCobolField c_3_SALES;
  private AbstractCobolField c_2_data;
  private AbstractCobolField c_1_data;

  /* Attributes */

  private CobolFieldAttribute a_4_NumericDisplay_Digits1_Scale0;
  private CobolFieldAttribute a_3_NumericDisplay_Digits5_Scale0;
  private CobolFieldAttribute a_2_Group;
  private CobolFieldAttribute a_1_Alphanumeric;



  /* String literals */
  public static final byte[] str_5_SALES = CobolUtil.stringToBytes("SALES PROCESSING COMPLETED");
  public static final byte[] str_4_SALES = CobolUtil.stringToBytes("SALES RECORDS PROCESSED: ");
  public static final byte[] str_3_RAW = CobolUtil.stringToBytes("RAW RECORD: ");
  public static final byte[] str_2_SALES = CobolUtil.stringToBytes("SALES PROCESSING STARTED");
  public static final byte[] str_1_data = CobolUtil.stringToBytes("data/out/sales-report.dat");
  public static final byte[] str_0_data = CobolUtil.stringToBytes("data/in/sales-input.dat");
  /* File SLS-FILE */
  private CobolFile		h_SLS_FILE = null;
  private byte[]	h_SLS_FILE_status = new byte[4];
  /* File RPT-FILE */
  private CobolFile		h_RPT_FILE = null;
  private byte[]	h_RPT_FILE_status = new byte[4];

  /* Sections and Labels */
  private final static int l_SALESPROG = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__MAIN_SECTION = 3;
  private final static int l_MAIN_SECTION__PROCESS_SALE = 4;
  private final static int l_Default_Error_Handler = 5;

  private CobolRunnable call_SALESCALC = null;
}
