/* Generated by opensource COBOL 4J 2.0.0 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import jp.osscons.opensourcecobol.libcobj.sql.*;
import java.util.Optional;

public class SALESCALC implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return SALESCALC_(0, argStorages);
  }

  @Override
  public void cancel() {
    SALESCALC_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute (String CALC_LINKAGE) {
    this.f_CALC_LINKAGE.setDataStorage(new CobolDataStorage(38));
    this.f_CALC_LINKAGE.moveFrom(CALC_LINKAGE);
    this.b_CALC_LINKAGE = this.f_CALC_LINKAGE.getDataStorage();
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode,
      new CobolResultString(f_CALC_LINKAGE.getString())
    );
  }

  public int SALESCALC_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    this.b_CALC_LINKAGE = 0 < argStorages.length ? argStorages[0] : null;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	d0.clear();
    	d0.setScale(0);
    	d1.clear();
    	d1.setScale(0);
    	d2.clear();
    	d2.setScale(0);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);
    CobolResolve.pushCallStackList ("SALESCALC");

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("SALESCALC");

      /* Initialize decimal numbers */
      d0.decimalInit();
      d1.decimalInit();
      d2.decimalInit();

      b_RETURN_CODE.set((int)0);
      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      /* Entry dispatch */
      execEntry(l_SALESCALC);

    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolResolve.popCallStackList();
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_SALESCALC]);
      }
    },
    /* Entry SALESCALC */
    new CobolControl(l_SALESCALC, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__CALC_LOGIC]);
      }
    },
    /* CALC-LOGIC */
    new CobolControl(l_MAIN_SECTION__CALC_LOGIC, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolStopRunException {
        /* src/SALESCALC.cob:8: COMPUTE */
        {
          {
            {
              d0.set (b_CALC_LINKAGE.getNumdisp(5));
              d2.setField (new GetAbstractCobolField() {
                public AbstractCobolField run() {
                  f_LK_UNIT_PRICE__CALC_LINKAGE.setDataStorage(b_CALC_LINKAGE.getSubDataStorage(5));
                  return f_LK_UNIT_PRICE__CALC_LINKAGE;
                }
              }.run());
              d0.mul (d2);
              d1.set (1);
              d2.setField (new GetAbstractCobolField() {
                public AbstractCobolField run() {
                  f_LK_DISCOUNT__CALC_LINKAGE.setDataStorage(b_CALC_LINKAGE.getSubDataStorage(14));
                  return f_LK_DISCOUNT__CALC_LINKAGE;
                }
              }.run());
              d1.sub (d2);
              d0.mul (d1);
              d0.getField (new GetAbstractCobolField() {
                public AbstractCobolField run() {
                  f_LK_TOTAL__CALC_LINKAGE.setDataStorage(b_CALC_LINKAGE.getSubDataStorage(17));
                  return f_LK_TOTAL__CALC_LINKAGE;
                }
              }.run(), 4);
            }
          }
        }
        /* src/SALESCALC.cob:10: EVALUATE */
        {
          if (((long)new GetAbstractCobolField() {
            public AbstractCobolField run() {
              f_LK_TOTAL__CALC_LINKAGE.setDataStorage(b_CALC_LINKAGE.getSubDataStorage(17));
              return f_LK_TOTAL__CALC_LINKAGE;
            }
          }.run().cmpInteger (50000) >  0L))
            {
              /* src/SALESCALC.cob:12: MOVE */
              {
                b_CALC_LINKAGE.getSubDataStorage(28).setBytes (str_0_PLATINUM, 10);
              }
            }
          else
            if (((long)new GetAbstractCobolField() {
              public AbstractCobolField run() {
                f_LK_TOTAL__CALC_LINKAGE.setDataStorage(b_CALC_LINKAGE.getSubDataStorage(17));
                return f_LK_TOTAL__CALC_LINKAGE;
              }
            }.run().cmpInteger (10000) >  0L))
              {
                /* src/SALESCALC.cob:14: MOVE */
                {
                  b_CALC_LINKAGE.getSubDataStorage(28).setBytes (str_1_GOLD, 10);
                }
              }
            else
              if (((long)new GetAbstractCobolField() {
                public AbstractCobolField run() {
                  f_LK_TOTAL__CALC_LINKAGE.setDataStorage(b_CALC_LINKAGE.getSubDataStorage(17));
                  return f_LK_TOTAL__CALC_LINKAGE;
                }
              }.run().cmpInteger (1000) >  0L))
                {
                  /* src/SALESCALC.cob:16: MOVE */
                  {
                    b_CALC_LINKAGE.getSubDataStorage(28).setBytes (str_2_SILVER, 10);
                  }
                }
              else
                {
                  /* src/SALESCALC.cob:18: MOVE */
                  {
                    b_CALC_LINKAGE.getSubDataStorage(28).setBytes (str_3_BRONZE, 10);
                  }
                }
        }
        /* src/SALESCALC.cob:20: GOBACK */
        {
          if(true) return Optional.of(contList[contList.length - 1]);
        }
        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new SALESCALC().SALESCALC_(0);
    CobolStopRunException.stopRun();
  }

  public SALESCALC()
  {
    init();
  }

  public void init() 
  {
    /* Decimal structures */

    d0 = new CobolDecimal();
    d1 = new CobolDecimal();
    d2 = new CobolDecimal();

    /* Data storage */

    cob_unifunc = null;

    /* PROGRAM-ID : SALESCALC */
    b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */

    /* End of data storage */


    initAttr();

    /* Fields */

    /* PROGRAM-ID : SALESCALC */
    f_LK_UNIT_PRICE__CALC_LINKAGE	= CobolFieldFactory.makeCobolField(9, (CobolDataStorage)null, a_1_NumericDisplay_Digits9_Scale2);	/* LK-UNIT-PRICE */
    f_LK_DISCOUNT__CALC_LINKAGE	= CobolFieldFactory.makeCobolField(3, (CobolDataStorage)null, a_2_NumericDisplay_Digits3_Scale2);	/* LK-DISCOUNT */
    f_LK_TOTAL__CALC_LINKAGE	= CobolFieldFactory.makeCobolField(11, (CobolDataStorage)null, a_3_NumericDisplay_Digits11_Scale2);	/* LK-TOTAL */

    /* End of fields */


    /* Call parameters */
    f_CALC_LINKAGE = CobolFieldFactory.makeCobolField(38, (CobolDataStorage)null, a_4_Group);
  }

  private void initAttr() {
    /* Attributes */

    a_1_NumericDisplay_Digits9_Scale2 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 9,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_2_NumericDisplay_Digits3_Scale2 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 3,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_3_NumericDisplay_Digits11_Scale2 = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_NUMERIC_DISPLAY,
      /* digits= */ 11,
      /* scale= */ 2,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);
    a_4_Group = new CobolFieldAttribute(
      CobolFieldAttribute.COB_TYPE_GROUP,
      /* digits= */ 0,
      /* scale= */ 0,
      CobolFieldAttribute.COB_FLAG_NOT_SPECIFIED,
      /* pic= */ null);

  }

  /* Decimal structures */

  private CobolDecimal d0;
  private CobolDecimal d1;
  private CobolDecimal d2;

  /* Data storage */

  /* PROGRAM-ID : SALESCALC */
  public CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : SALESCALC */
  private AbstractCobolField f_LK_UNIT_PRICE__CALC_LINKAGE;	/* LK-UNIT-PRICE */
  private AbstractCobolField f_LK_DISCOUNT__CALC_LINKAGE;	/* LK-DISCOUNT */
  private AbstractCobolField f_LK_TOTAL__CALC_LINKAGE;	/* LK-TOTAL */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Attributes */

  private CobolFieldAttribute a_4_Group;
  private CobolFieldAttribute a_3_NumericDisplay_Digits11_Scale2;
  private CobolFieldAttribute a_2_NumericDisplay_Digits3_Scale2;
  private CobolFieldAttribute a_1_NumericDisplay_Digits9_Scale2;

  /* Call parameters */
  private AbstractCobolField f_CALC_LINKAGE;
  private CobolDataStorage b_CALC_LINKAGE;


  /* String literals */
  public static final byte[] str_3_BRONZE = CobolUtil.stringToBytes("BRONZE    ");
  public static final byte[] str_2_SILVER = CobolUtil.stringToBytes("SILVER    ");
  public static final byte[] str_1_GOLD = CobolUtil.stringToBytes("GOLD      ");
  public static final byte[] str_0_PLATINUM = CobolUtil.stringToBytes("PLATINUM  ");

  /* Sections and Labels */
  private final static int l_SALESCALC = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__CALC_LOGIC = 3;
  private final static int l_Default_Error_Handler = 4;

}
