"""
generators/native_java/program.py

Top-level generator: walks a SemanticIR and assembles a complete
Java source file for a single COBOL program.

Track-B contract:
  - Zero dependency on libcobj.jar, jp.osscons, COBOL4J runtime
  - Generated Java imports only: java.*, java.math.*, java.io.*,
    org.springframework.* (where evidence requires it),
    com.platform.modernized.runtime.* (our own runtime helpers)
  - The base package is read from MigrationConfig.base_package; it is
    never hardcoded.

Produces:
  <ProgramName>.java  — the main class
  pom.xml             — Maven build descriptor
"""
from __future__ import annotations

import os
import re
import textwrap
from typing import Optional

from engine.semantic.semantic_ir import SemanticIR, SemanticIRNode
from generators.native_java.types import (
    JavaTypeInfo, map_data_item, to_java_var, to_java_class,
)
from generators.native_java.statements import translate_statement, GeneratorContext


class NativeJavaGenerator:
    """
    Generates a native Java Spring Boot application from a SemanticIR.

    Parameters
    ----------
    ir:
        The parsed SemanticIR for the COBOL program.
    program_name:
        The COBOL PROGRAM-ID value.
    base_package:
        Java base package (e.g. 'com.platform.modernized').
        Read from MigrationConfig — never hardcoded.
    """

    RUNTIME_PACKAGE = "com.platform.modernized.runtime"

    def __init__(
        self,
        ir: SemanticIR,
        program_name: str,
        base_package: str = "com.platform.modernized",
    ) -> None:
        self.ir = ir
        self.program_name = program_name
        self.class_name = to_java_class(program_name)
        self.base_package = base_package
        self.ctx = GeneratorContext(program_name=program_name)

    def generate(self, out_dir: str) -> dict[str, str]:
        """
        Generate Java source and pom.xml into out_dir.

        Returns
        -------
        Dict mapping filename -> absolute path for each generated file.
        """
        # Standard Maven layout
        java_dir = os.path.join(
            out_dir, "src", "main", "java",
            *self.base_package.split("."),
        )
        os.makedirs(java_dir, exist_ok=True)
        os.makedirs(out_dir, exist_ok=True)

        # --- Build field registry ---
        self._build_field_registry()

        # --- Generate Java source ---
        java_src = self._emit_java()
        java_path = os.path.join(java_dir, f"{self.class_name}.java")
        _write(java_path, java_src)

        # --- Generate pom.xml ---
        pom_src = self._emit_pom()
        pom_path = os.path.join(out_dir, "pom.xml")
        _write(pom_path, pom_src)

        return {
            f"{self.class_name}.java": java_path,
            "pom.xml": pom_path,
        }

    # ── Field registry ────────────────────────────────────────────────────────

    def _build_field_registry(self) -> None:
        """Populate ctx.fields from DATA_ITEM nodes in the IR."""
        for node in self.ir.nodes_of_kind("DATA_ITEM"):
            p = node.properties
            name = p.get("name", "")
            if not name:
                continue
            pic = p.get("pic", p.get("picture", ""))
            usage = p.get("usage", "DISPLAY")
            java_info = map_data_item(pic, usage,
                                      signed=p.get("signed"),
                                      digits=p.get("digits"),
                                      scale=p.get("scale"))
            self.ctx.fields[name.upper().replace("-", "_")] = java_info

    # ── Java source ───────────────────────────────────────────────────────────

    def _emit_java(self) -> str:
        lines = []

        # Package + imports
        lines.append(f"package {self.base_package};")
        lines.append("")
        lines.append("// Generated by cobol-java-platform")
        lines.append(f"// COBOL PROGRAM-ID: {self.program_name}")
        lines.append("// Track B: native Java — zero dependency on legacy COBOL runtime")
        lines.append("")
        lines.append("import java.math.BigDecimal;")
        lines.append("import java.math.RoundingMode;")
        lines.append("")

        # Class
        lines.append(f"public class {self.class_name} {{")
        lines.append("")

        # Fields
        lines.extend(self._emit_fields())
        lines.append("")

        # main()
        lines.append("    public static void main(String[] args) {")
        lines.append(f"        new {self.class_name}().run();")
        lines.append("    }")
        lines.append("")

        # run() = PROCEDURE DIVISION
        lines.append("    public void run() {")
        lines.extend(self._emit_procedure())
        lines.append("    }")
        lines.append("")

        # Paragraph methods
        lines.extend(self._emit_paragraphs())

        lines.append("}")
        return "\n".join(lines) + "\n"

    def _emit_fields(self) -> list[str]:
        """Emit Java field declarations for WORKING-STORAGE items."""
        lines = []
        # COBOL Special Registers
        lines.append("    private int return_code = 0; // COBOL RETURN-CODE register")
        for node in self.ir.nodes_of_kind("DATA_ITEM"):
            p = node.properties
            name = p.get("name", "")
            level = p.get("level", 99)
            section = p.get("section", "")
            if not name or level == 88:
                continue
            # Only Working-Storage and Linkage-Section fields
            if section not in ("WORKING-STORAGE", "LINKAGE", ""):
                continue

            java_name = to_java_var(name)
            ti = self.ctx.fields.get(name.upper().replace("-", "_"))
            if ti is None:
                lines.append(f"    private String {java_name} = \"\"; // {name}")
                continue

            init = _init_from_node(p, ti)
            comment = f"// {name}" + (f" PIC {p.get('pic','')}" if p.get('pic') else "")
            lines.append(f"    private {ti.java_type} {java_name} = {init}; {comment}")

        return lines

    def _emit_procedure(self) -> list[str]:
        """Emit statements for the main procedure entry point."""
        lines = []
        # Find first paragraph or main entry point
        first_para = None
        for node in self.ir.nodes.values():
            if node.kind == "PARAGRAPH":
                first_para = node.properties.get("name")
                break

        if first_para:
            lines.append(f"        {to_java_var(first_para)}();")
        else:
            # Emitted inline if no paragraphs
            for node in self.ir.nodes.values():
                if node.kind == "STATEMENT":
                    for sl in translate_statement(node.properties, self.ctx):
                        lines.append(f"        {sl}")
        return lines

    def _emit_paragraphs(self) -> list[str]:
        """Emit one Java method per COBOL paragraph."""
        lines = []
        paragraphs: dict[str, list] = {}
        order: list[str] = []

        current_para = None
        for node in self.ir.nodes.values():
            if node.kind == "PARAGRAPH":
                current_para = node.properties.get("name", "")
                if current_para and current_para not in paragraphs:
                    paragraphs[current_para] = []
                    order.append(current_para)
                    self.ctx.paragraphs.add(current_para)
            elif node.kind == "STATEMENT" and current_para:
                paragraphs[current_para].append(node.properties)

        for para_name in order:
            stmts = paragraphs[para_name]
            method_name = to_java_var(para_name)
            lines.append(f"    // Paragraph: {para_name}")
            lines.append(f"    private void {method_name}() {{")
            if stmts:
                for stmt in stmts:
                    for sl in translate_statement(stmt, self.ctx):
                        lines.append(f"        {sl}")
            else:
                lines.append(f"        // (empty paragraph)")
            lines.append("    }")
            lines.append("")

        return lines

    # ── pom.xml ───────────────────────────────────────────────────────────────

    def _emit_pom(self) -> str:
        return f"""\
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>{self.base_package}</groupId>
    <artifactId>{self.program_name.lower()}</artifactId>
    <version>1.0.0-GENERATED</version>
    <packaging>jar</packaging>

    <name>Generated: {self.program_name}</name>
    <description>
        Native Java translation of COBOL program {self.program_name}.
        Generated by cobol-java-platform. Track B: zero libcobj dependency.
    </description>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>{self.base_package}.{self.class_name}</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _init_from_node(props: dict, ti: JavaTypeInfo) -> str:
    """Derive the Java initialisation expression from PIC VALUE clause."""
    val = props.get("value", props.get("initial_value"))
    if val is None:
        return ti.init_expr

    val_str = str(val).strip()
    if val_str.upper() in ("ZERO", "ZEROS", "ZEROES"):
        return ti.init_expr if "0" in ti.init_expr or "ZERO" in ti.init_expr else "0"
    if val_str.upper() in ("SPACE", "SPACES"):
        return '""'
    if val_str.upper() in ("HIGH-VALUE", "HIGH-VALUES"):
        return '"\\xFF"'
    if ti.is_alpha:
        inner = val_str.strip("'\"")
        return f'"{inner}"'
    if ti.is_numeric:
        try:
            int(val_str)
            return val_str
        except ValueError:
            try:
                float(val_str)
                return val_str
            except ValueError:
                pass
    return ti.init_expr


def _write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
