"""Phase 9 - Pipeline Execution Manifest Tests

Verifies:
- Required keys present
- Stage/state consistency
- Final verdict consistency
- Manifest generated by stage_report()
- Manifest included in package ZIP
"""
import json
import os
import sys
import zipfile
import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import cobol_migrate as cm

REQUIRED_TOP_KEYS = {
    "schema_version", "execution_id", "repository", "started_at",
    "completed_at", "stages", "diagnostics", "dependency_audit",
    "build", "execution", "equivalence", "negative_equivalence",
    "traceability", "artifacts", "final_verdict",
}


@pytest.fixture
def pipeline_after_report(tmp_path):
    """Run just enough pipeline setup so stage_report() can execute."""
    repo = tmp_path / "repo"
    repo.mkdir()
    out = tmp_path / "out"
    out.mkdir()
    (repo / "DUMMY.cob").write_text(
        "       IDENTIFICATION DIVISION.\n"
        "       PROGRAM-ID. DUMMY.\n"
        "       PROCEDURE DIVISION.\n"
        "           STOP RUN.\n",
        encoding="utf-8",
    )
    p = cm.Pipeline(str(repo), str(out), pull=False)
    # Minimal state so stage_report() can run (it needs ingest_hashes)
    p.state["data"]["ingest_hashes"] = {}
    p.state["data"]["discover"] = {
        "programs": [{"source": "DUMMY.cob", "program_id": "DUMMY", "lines": 10}],
        "format": "free",
        "entry": "DUMMY",
        "copybook_dirs": [],
        "copy_deps": {},
        "missing_copybooks": [],
        "call_graph": {},
        "file_assigns": {}
    }
    p.state["data"]["transpile"] = {
        "status": {"DUMMY.cob": True},
        "image": "opensourcecobol/opensourcecobol4j:2.0.0",
        "all_at_once_rc": 0,
        "n_ok": 1,
        "n_total": 1
    }
    p.state["data"]["collect"] = {
        "stub_flags": [],
        "java_files": ["DUMMY.java"],
        "loc_generated": 100
    }
    p.state["data"]["preserve"] = {
        "jar": "libcobj.jar",
        "version": "2.0.0",
        "size": 1000,
        "sha256": "123456789"
    }
    p.state["data"]["execute"] = {
        "command": "java -jar",
        "rc": 0,
        "stdout_tail": "success"
    }
    p.state["data"]["compare"] = {
        "rows": [],
        "verdict_counts": {"match": 0, "differ": 0},
        "checks": []
    }
    # Mark some stages as done so _compute_verdict has evidence
    p.state["stages"]["ingest"] = {"status": "done", "started_at": "2026-01-01T00:00:00+00:00",
                                    "completed_at": "2026-01-01T00:01:00+00:00"}
    p.state["data"]["baseline_files"] = []  # EQUIVALENCE_UNVERIFIED
    p.save_state()
    return p, out


class TestManifestRequiredKeys:
    def test_required_keys_present(self, pipeline_after_report):
        p, out = pipeline_after_report
        ok, detail, artifacts = p.stage_report()
        assert ok
        manifest_path = out / "pipeline_execution_manifest.json"
        assert manifest_path.exists(), "pipeline_execution_manifest.json must be generated"
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
        missing = REQUIRED_TOP_KEYS - set(data.keys())
        assert not missing, f"Manifest missing required keys: {missing}"

    def test_schema_version_present(self, pipeline_after_report):
        p, out = pipeline_after_report
        p.stage_report()
        data = json.loads((out / "pipeline_execution_manifest.json").read_text(encoding="utf-8"))
        assert data["schema_version"] == "1.0"

    def test_execution_id_is_string(self, pipeline_after_report):
        p, out = pipeline_after_report
        p.stage_report()
        data = json.loads((out / "pipeline_execution_manifest.json").read_text(encoding="utf-8"))
        assert isinstance(data["execution_id"], str) and data["execution_id"]

    def test_stages_reflect_pipeline_state(self, pipeline_after_report):
        p, out = pipeline_after_report
        p.stage_report()
        data = json.loads((out / "pipeline_execution_manifest.json").read_text(encoding="utf-8"))
        # ingest was marked done in fixture
        assert "ingest" in data["stages"], "stages dict must include ingest"
        assert data["stages"]["ingest"]["status"] == "done"

    def test_final_verdict_not_production_ready_without_gates(self, pipeline_after_report):
        """Without full gate evidence, manifest must not claim MVP_CERTIFIED."""
        p, out = pipeline_after_report
        p.stage_report()
        data = json.loads((out / "pipeline_execution_manifest.json").read_text(encoding="utf-8"))
        assert data["final_verdict"] != "MVP_CERTIFIED", (
            f"Manifest claimed MVP_CERTIFIED without evidence; got {data['final_verdict']}"
        )

    def test_final_verdict_matches_compute_verdict(self, pipeline_after_report):
        """Manifest final_verdict must equal _compute_verdict()."""
        p, out = pipeline_after_report
        expected = p._compute_verdict()
        p.stage_report()
        data = json.loads((out / "pipeline_execution_manifest.json").read_text(encoding="utf-8"))
        assert data["final_verdict"] == expected

    def test_artifacts_list_contains_only_real_files(self, pipeline_after_report):
        p, out = pipeline_after_report
        p.stage_report()
        data = json.loads((out / "pipeline_execution_manifest.json").read_text(encoding="utf-8"))
        for path in data["artifacts"]:
            assert os.path.exists(path), f"Artifact listed in manifest does not exist: {path}"


class TestManifestInPackage:
    def test_manifest_in_zip(self, pipeline_after_report):
        """stage_package() must include pipeline_execution_manifest.json in the ZIP."""
        p, out = pipeline_after_report
        p.stage_report()
        # Create minimal structure expected by stage_package
        generated = out / "generated"
        generated.mkdir(exist_ok=True)
        ok, detail, artifacts = p.stage_package()
        assert ok
        pkg_zip = out / "modernized-package.zip"
        assert pkg_zip.exists()
        with zipfile.ZipFile(str(pkg_zip)) as zf:
            names = zf.namelist()
        assert "reports/pipeline_execution_manifest.json" in names, (
            f"pipeline_execution_manifest.json not in ZIP. Found: {names}"
        )

    def test_zip_manifest_matches_generated_manifest(self, pipeline_after_report):
        """Content of manifest in ZIP must match the generated manifest file."""
        p, out = pipeline_after_report
        p.stage_report()
        (out / "generated").mkdir(exist_ok=True)
        p.stage_package()
        expected = json.loads((out / "pipeline_execution_manifest.json").read_text(encoding="utf-8"))
        pkg_zip = out / "modernized-package.zip"
        with zipfile.ZipFile(str(pkg_zip)) as zf:
            actual = json.loads(zf.read("reports/pipeline_execution_manifest.json").decode("utf-8"))
        # Core fields must match (execution_id anchors the identity)
        assert actual["execution_id"] == expected["execution_id"]
        assert actual["final_verdict"] == expected["final_verdict"]
        assert actual["schema_version"] == expected["schema_version"]
