CREATE TABLE INS_CUSTOMER (
 CUSTOMER_ID CHAR(6) NOT NULL PRIMARY KEY, CUSTOMER_NAME VARCHAR(30),
 CUSTOMER_STATUS CHAR(1), CITY VARCHAR(20), STATE_CODE CHAR(2), RISK_LEVEL CHAR(1)
);
CREATE TABLE INS_POLICY (
 POLICY_ID CHAR(10) NOT NULL PRIMARY KEY, CUSTOMER_ID CHAR(6),
 POLICY_TYPE CHAR(2), POLICY_STATUS CHAR(1), CURRENCY_CODE CHAR(3),
 COVER_LIMIT DECIMAL(13,2), DEDUCTIBLE DECIMAL(11,2),
 EFFECTIVE_DATE CHAR(8), EXPIRY_DATE CHAR(8)
);
CREATE TABLE INS_CLAIM (
 CLAIM_ID CHAR(12) NOT NULL PRIMARY KEY, POLICY_ID CHAR(10),
 CLAIM_TYPE CHAR(2), CLAIM_DATE CHAR(8), LOSS_AMOUNT DECIMAL(11,2),
 CLAIM_STATUS CHAR(2), APPROVED_AMOUNT DECIMAL(13,2)
);
CREATE TABLE INS_CLAIM_AUDIT (
 CLAIM_ID CHAR(12), POLICY_ID CHAR(10), STATUS VARCHAR(20),
 APPROVED_AMOUNT DECIMAL(13,2)
);
