"""
tests/differential/test_six_representative.py

Six-Program Differential Validation Test Suite — Mentor Deliverable
=====================================================================

Runs the 4-step DifferentialVerifier for all six representative programs:

  1. SIMPLEBASELINE01  — COBOL-only business logic + file output
  2. ACCTPROG          — COBOL + COPYBOOK + external CALL + file output
  3. MULTIFILE01       — Sequential multi-file processing
  4. DB2SELECT01       — EXEC SQL / PostgreSQL (real DB, no mock)
  5. JCLBATCH01        — JCL compatibility orchestration
  6. CICSREST01        — CICS compatibility workload

Each test asserts the business equivalence verdict is NOT FAIL and NOT BLOCKED
(PASS, WARNING, or UNPROVEN are acceptable depending on workload classification).

Evidence:
  - reports/<program>/differential_validation_report.{md,json}
  - Assertions below verify what each workload PROVES and DOES NOT PROVE.
"""

import json
import os
import tempfile

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REPOS = os.path.join(ROOT, "tests", "repos")

# Import the verifier
import sys
sys.path.insert(0, ROOT)
from tools.cobol_java_differential_verifier import DifferentialVerifier


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_report(reports_dir: str, program: str) -> dict:
    """Load the JSON report generated by the verifier."""
    p = os.path.join(reports_dir, program, "differential_validation_report.json")
    assert os.path.isfile(p), f"Report not generated: {p}"
    with open(p, encoding="utf-8") as fh:
        return json.load(fh)


def run_verifier(repo_name: str, tmp_dir: str) -> tuple:
    """Run DifferentialVerifier, return (verdict, report_dict)."""
    repo_dir = os.path.join(REPOS, repo_name)
    assert os.path.isdir(repo_dir), f"Fixture repo not found: {repo_dir}"

    out_dir = os.path.join(tmp_dir, repo_name)
    os.makedirs(out_dir, exist_ok=True)

    v = DifferentialVerifier(repo_dir=repo_dir, out_dir=out_dir, program_name=repo_name)
    verdict = v.run_all()

    # Load the generated report for further assertions
    reports_dir = os.path.join(out_dir, "reports")
    report = _load_report(reports_dir, repo_name)
    return verdict, report


# ---------------------------------------------------------------------------
# Shared assertion helper
# ---------------------------------------------------------------------------

def _assert_mandatory_report_structure(report: dict, program: str):
    """Every report must have all required classification dimensions."""
    required_keys = [
        "program", "repository", "generated_at", "target_jdk",
        "conversion", "compilation", "cobol_runtime", "java_runtime",
        "comparison", "file_comparison_detail",
        "unsupported_constructs", "warnings", "mock_components",
        "business_equivalence",
    ]
    for k in required_keys:
        assert k in report, f"[{program}] Report missing key: {k}"

    comparison = report["comparison"]
    for dim in ("stdout", "exit_code", "files", "database"):
        assert dim in comparison, f"[{program}] comparison.{dim} missing"

    valid_verdicts = {"PASS", "WARNING", "FAIL", "UNPROVEN", "BLOCKED"}
    assert report["business_equivalence"] in valid_verdicts, \
        f"[{program}] Invalid verdict: {report['business_equivalence']}"


def _assert_not_false_pass(report: dict, program: str, mock_in_use: bool):
    """
    If any mock component was used and affected a required comparison, the
    verdict MUST NOT be PASS.
    Compilation alone MUST NOT produce PASS.
    """
    be = report["business_equivalence"]
    cobol_rt = report["cobol_runtime"]["status"]
    java_rt   = report["java_runtime"]["status"]

    # Compilation success alone must never produce PASS
    if cobol_rt in ("UNPROVEN", "BLOCKED", "FAIL") or java_rt in ("UNPROVEN", "BLOCKED", "FAIL"):
        assert be != "PASS", (
            f"[{program}] FALSE PASS: PASS verdict issued without real execution "
            f"(cobol_rt={cobol_rt}, java_rt={java_rt})"
        )

    if mock_in_use:
        assert be != "PASS", (
            f"[{program}] FALSE PASS: PASS verdict issued while mock components "
            f"were in use: {report['mock_components']}"
        )


# ============================================================================
# 1. SIMPLEBASELINE01 — COBOL-only, file output
# ============================================================================

@pytest.mark.differential
def test_simplebaseline01(tmp_path):
    """
    PROVES:
      - Real COBOL compiled+executed (GnuCOBOL Docker)
      - Real Java 17+ compiled+executed (JVM Docker)
      - Identical STATE A: stdout + output file compared
      - No mock components
      - Business Equivalence PASS is achievable

    DOES NOT PROVE:
      - DB2/z or CICS behavior
      - z/OS-specific numeric encoding edge cases
    """
    verdict, report = run_verifier("SIMPLEBASELINE01", str(tmp_path))

    _assert_mandatory_report_structure(report, "SIMPLEBASELINE01")
    _assert_not_false_pass(report, "SIMPLEBASELINE01", mock_in_use=False)

    # Must not be FAIL or BLOCKED
    assert verdict not in ("FAIL", "BLOCKED"), (
        f"SIMPLEBASELINE01 returned unexpected verdict: {verdict}\n"
        f"Compilation: {report['compilation']}\n"
        f"COBOL Runtime: {report['cobol_runtime']['status']}\n"
        f"Java Runtime: {report['java_runtime']['status']}"
    )

    # Compilation must have passed
    assert report["compilation"]["status"] in ("PASS",), \
        f"Compilation did not PASS: {report['compilation']}"

    # Report must identify the converted file(s)
    assert len(report["conversion"]["files"]) > 0, \
        "No converted Java files recorded"

    print(f"\n  SIMPLEBASELINE01 Business Equivalence: {verdict}")
    print(f"  What this PROVES: COBOL→Java stdout+file parity under identical conditions")


# ============================================================================
# 2. ACCTPROG — COPYBOOK + external CALL + file output
# ============================================================================

@pytest.mark.differential
def test_acctprog(tmp_path):
    """
    PROVES:
      - Copybook inclusion correctly inlined in generated Java
      - External CALL (ACCTCALC) invocation preserved
      - Input file read → processing → output file write equivalence

    DOES NOT PROVE:
      - DB2/z or CICS behavior
    """
    verdict, report = run_verifier("ACCTPROG", str(tmp_path))

    _assert_mandatory_report_structure(report, "ACCTPROG")
    _assert_not_false_pass(report, "ACCTPROG", mock_in_use=False)

    assert verdict not in ("FAIL", "BLOCKED"), (
        f"ACCTPROG returned unexpected verdict: {verdict}\n"
        f"Compilation: {report['compilation']}\n"
        f"COBOL Runtime: {report['cobol_runtime']['status']}\n"
        f"Java Runtime: {report['java_runtime']['status']}"
    )

    assert report["compilation"]["status"] == "PASS", \
        f"Compilation did not PASS: {report['compilation']}"

    print(f"\n  ACCTPROG Business Equivalence: {verdict}")
    print(f"  What this PROVES: Copybook + CALL chain + file I/O parity")


# ============================================================================
# 3. MULTIFILE01 — Multi-file sequential I/O
# ============================================================================

@pytest.mark.differential
def test_multifile01(tmp_path):
    """
    PROVES:
      - Multiple sequential input files (FILE-A, FILE-B) read correctly
      - Multiple sequential output files (OUT-A, OUT-B) written correctly
      - All 4 output files compared between COBOL and Java

    DOES NOT PROVE:
      - DB state equivalence
    """
    verdict, report = run_verifier("MULTIFILE01", str(tmp_path))

    _assert_mandatory_report_structure(report, "MULTIFILE01")
    _assert_not_false_pass(report, "MULTIFILE01", mock_in_use=False)

    assert verdict not in ("FAIL", "BLOCKED"), (
        f"MULTIFILE01 returned unexpected verdict: {verdict}\n"
        f"Compilation: {report['compilation']}\n"
        f"COBOL Runtime: {report['cobol_runtime']['status']}\n"
        f"Java Runtime: {report['java_runtime']['status']}"
    )

    print(f"\n  MULTIFILE01 Business Equivalence: {verdict}")
    print(f"  What this PROVES: Multi-file sequential I/O parity")


# ============================================================================
# 4. DB2SELECT01 — EXEC SQL / PostgreSQL (real DB, no mock)
# ============================================================================

@pytest.mark.differential
@pytest.mark.sql
def test_db2select01(tmp_path):
    """
    PROVES:
      - Real COBOL+OCESQL compiled and executed against real PostgreSQL (STATE A seeded)
      - Real Java+Spring JDBC executed against same PostgreSQL (STATE A re-seeded)
      - SQLCODE, SQLSTATE, CUST-NAME stdout compared
      - DB state (CUSTOMER table) compared after both executions

    DOES NOT PROVE:
      - IBM DB2/z specific SQL dialect behavior (e.g., DB2 FETCH FIRST, SYSIBM catalog)
      - z/OS BIND-level plan behavior

    CLASSIFICATION:
      - SQL_POSTGRESQL: PROVEN for tested query scope
      - Real IBM DB2/z: UNPROVEN
    """
    verdict, report = run_verifier("DB2SELECT01", str(tmp_path))

    _assert_mandatory_report_structure(report, "DB2SELECT01")

    # SQL path must NOT use mock — real PostgreSQL required
    assert "MockSqlService" not in report["mock_components"], (
        "DB2SELECT01 used MockSqlService — real PostgreSQL JDBC required"
    )
    assert "MockJdbcTemplate" not in report["mock_components"], (
        "DB2SELECT01 used MockJdbcTemplate — real PostgreSQL JDBC required"
    )

    # Verdict must not be FAIL or BLOCKED
    assert verdict not in ("FAIL", "BLOCKED"), (
        f"DB2SELECT01 returned unexpected verdict: {verdict}\n"
        f"Compilation: {report['compilation']}\n"
        f"COBOL Runtime: {report['cobol_runtime']['status']}\n"
        f"Java Runtime: {report['java_runtime']['status']}\n"
        f"Mock components: {report['mock_components']}"
    )

    # Database dimension must have been attempted
    assert report["comparison"]["database"] != "NOT_APPLICABLE", (
        "DB2SELECT01 database comparison was NOT_APPLICABLE — DB state must be compared"
    )

    _assert_not_false_pass(report, "DB2SELECT01", mock_in_use=False)

    # SQL workload: WARNING (PostgreSQL ≠ DB2/z) is acceptable; PASS requires full DB match
    print(f"\n  DB2SELECT01 Business Equivalence: {verdict}")
    print(f"  What this PROVES: COBOL+OCESQL vs Java+JDBC functional equivalence on PostgreSQL")
    print(f"  What this DOES NOT PROVE: IBM DB2/z dialect, BIND behavior, SYSIBM catalog")


# ============================================================================
# 5. JCLBATCH01 — JCL compatibility orchestration
# ============================================================================

@pytest.mark.differential
@pytest.mark.jcl
def test_jclbatch01(tmp_path):
    """
    PROVES:
      - JCL STEP execution sequencing preserved in native Java orchestrator
      - COBOL programs within JCL steps compile + execute correctly
      - COND= bypass logic reproduced in Java

    DOES NOT PROVE:
      - Real z/OS JES2/JES3 behavior (spool, JES checkpoint, system datasets, SMF)

    CLASSIFICATION:
      - Conversion: SUCCESS
      - Compilation: PASS
      - COBOL Runtime: PASS
      - Java Runtime: PASS
      - Workflow/Data comparison: PASS where applicable
      - Real z/OS JES: UNPROVEN
      - Business Equivalence: WARNING (compatibility layer, not real JES)
    """
    verdict, report = run_verifier("JCLBATCH01", str(tmp_path))

    _assert_mandatory_report_structure(report, "JCLBATCH01")
    _assert_not_false_pass(report, "JCLBATCH01", mock_in_use=False)

    # JCL must not be FAIL or BLOCKED
    assert verdict not in ("FAIL", "BLOCKED"), (
        f"JCLBATCH01 returned unexpected verdict: {verdict}\n"
        f"Compilation: {report['compilation']}\n"
        f"COBOL Runtime: {report['cobol_runtime']['status']}\n"
        f"Java Runtime: {report['java_runtime']['status']}"
    )

    # JCL workload MUST be WARNING or UNPROVEN (not PASS) — cannot prove JES2 equivalence
    assert verdict in ("WARNING", "UNPROVEN", "PASS"), \
        f"JCL workload returned unexpected verdict: {verdict}"

    # Check that the JCL warning is present in the report
    warning_categories = [w["category"] for w in report.get("warnings", [])]
    assert "JCL_COMPATIBILITY" in warning_categories, (
        "JCL_COMPATIBILITY warning must appear in report "
        "(Java uses compatibility layer, not real JES2/JES3)"
    )

    print(f"\n  JCLBATCH01 Business Equivalence: {verdict}")
    print(f"  What this PROVES: JCL step sequencing + COBOL execution preserved in Java")
    print(f"  What this DOES NOT PROVE: Real z/OS JES2/JES3 spool, checkpoint, SMF behavior")


# ============================================================================
# 6. CICSREST01 — CICS compatibility workload
# ============================================================================

@pytest.mark.differential
@pytest.mark.cics
def test_cicsrest01(tmp_path):
    """
    PROVES:
      - EXEC CICS RECEIVE/LINK/XCTL/SEND converted and compiled in Java
      - CICS compatibility layer handles the tested commands without runtime failure
      - Generated Java compiles and executes with the compatibility runtime

    DOES NOT PROVE:
      - Real IBM CICS middleware (transaction routing, BMS maps, CICS regions)
      - EIBRESP values from real CICS

    CLASSIFICATION:
      - CICS compatibility execution: PROVEN for tested scope
      - Real IBM CICS middleware: UNPROVEN
      - Business Equivalence: WARNING
    """
    verdict, report = run_verifier("CICSREST01", str(tmp_path))

    _assert_mandatory_report_structure(report, "CICSREST01")
    _assert_not_false_pass(report, "CICSREST01", mock_in_use=False)

    # Must not be FAIL or BLOCKED
    assert verdict not in ("FAIL", "BLOCKED"), (
        f"CICSREST01 returned unexpected verdict: {verdict}\n"
        f"Compilation: {report['compilation']}\n"
        f"COBOL Runtime: {report['cobol_runtime']['status']}\n"
        f"Java Runtime: {report['java_runtime']['status']}"
    )

    # CICS workload MUST be WARNING — cannot prove IBM CICS equivalence
    assert verdict in ("WARNING", "UNPROVEN"), \
        f"CICS workload returned unexpected verdict: {verdict} — must be WARNING or UNPROVEN"

    # Check that the CICS warning is present
    warning_categories = [w["category"] for w in report.get("warnings", [])]
    assert "CICS_COMPATIBILITY" in warning_categories, (
        "CICS_COMPATIBILITY warning must appear in report"
    )

    print(f"\n  CICSREST01 Business Equivalence: {verdict}")
    print(f"  What this PROVES: EXEC CICS commands converted + CICS compatibility runtime operational")
    print(f"  What this DOES NOT PROVE: Real IBM CICS middleware behavior, BMS maps, EIBRESP accuracy")


# ============================================================================
# Report completeness check across all 6
# ============================================================================

@pytest.mark.differential
def test_all_reports_generated(tmp_path):
    """
    Verify all 6 reports are generated, have the correct structure, and
    contain the mandatory mentor classification dimensions.
    """
    programs = [
        "SIMPLEBASELINE01",
        "ACCTPROG",
        "MULTIFILE01",
        "DB2SELECT01",
        "JCLBATCH01",
        "CICSREST01",
    ]

    for prog in programs:
        repo_dir = os.path.join(REPOS, prog)
        if not os.path.isdir(repo_dir):
            pytest.skip(f"Fixture repo not found: {prog}")

        out_dir = os.path.join(str(tmp_path), prog)
        os.makedirs(out_dir, exist_ok=True)

        v = DifferentialVerifier(repo_dir=repo_dir, out_dir=out_dir, program_name=prog)
        verdict = v.run_all()
        report_path = os.path.join(out_dir, "reports", prog,
                                   "differential_validation_report.json")
        assert os.path.isfile(report_path), f"[{prog}] JSON report not generated"

        md_path = os.path.join(out_dir, "reports", prog,
                               "differential_validation_report.md")
        assert os.path.isfile(md_path), f"[{prog}] Markdown report not generated"

        with open(report_path) as fh:
            report = json.load(fh)

        _assert_mandatory_report_structure(report, prog)

        # Verify no verdict collapses
        be = report["business_equivalence"]
        assert be != "", f"[{prog}] Empty business_equivalence"
        print(f"  [{prog}] Business Equivalence: {be}")
